spring:
  application:
    name: discovery-server

server:
  port: 9091

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery-server-service
      leaseRenewalIntervalInSeconds: 10
  instance:
    prefer-ip-address: true