
server:
  port: 9090

spring:
    application:
        name: config-server
    profiles:
        active: native
    cloud:
        config:
            server:
                native:
                    searchLocations: classpath:/config/